# Site settings
title: The Flux Resource Manager Framework
email: flux-discuss@lists.llnl.gov
description: > # this means to ignore newlines until "baseurl:"
  The Flux framework is a family of projects used to build site-customized
  resource management systems for High Performance Computing (HPC) data centers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://flux-framework.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  flux-framework

# Build settings
markdown: kramdown
